In [11]:
from glob import glob
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

In [12]:
def load_data(file, sheet_name):
    return pd.read_excel(file, sheet_name=sheet_name)

In [13]:
PATH = "C:/Users/withus/Desktop/sabin/data/lease/"
files = glob(PATH + '*.xlsx')

news = pd.DataFrame()
news_popular = pd.DataFrame()
twitter = pd.DataFrame()
blog = pd.DataFrame()
community = pd.DataFrame()

for file in files:
    twitter = pd.concat([twitter, load_data(file, '트위터')], axis=0)

## 트위터 Sheet

In [14]:
twitter.isna().sum()

Unnamed: 0    0
Unnamed: 1    0
Unnamed: 2    0
dtype: int64

In [15]:
twitter.columns = twitter.iloc[0]
twitter.drop(0, inplace=True, axis=0)
twitter = twitter[~twitter['내용'].str.contains('http')]
twitter = twitter[twitter['내용'].str.contains('[가-힣]')]
twitter = twitter[twitter['내용'].str.len() < 1000]

print(twitter.shape)
twitter.head()

(2496, 3)

,작성일,작성자,내용
3,2020/08/01,aa4wFmEnmw7I3nT,임대차3법을 막으려년 임대차3법이 무엇이 잘못됐는지 알아야 하지 않을까?\n임대차3...
4,2020/08/01,kicoo77,@TheMinjoo_Kr * 편법 탈법으로 투기하는 자들이 나쁜가? 투기로 부동산가...
5,2020/07/31,live_suyongso,오늘들은 임대차3법 관련 썰\n\n10월에 전세권자랑 전세금 올리고 재계약 할랬는데...
10,2020/12/12,uSTlqFPVb730Qa8,아동학대 발언하신 분이 임대차3법 발의한 박주민보다 욕을 더 먹는 게 말이 된다고 ...
11,2020/12/05,Vigilante_Aiden,아니 씨발 임대차 3법은 도대체 왜 단독으로 강행 통과시킨 건데? 그 때 임대차 3...

## TF-IDF

In [28]:
def tfdif(corpus):
    cv = CountVectorizer(ngram_range=(1, 2), max_features=1000)
    document_term_matrix = cv.fit_transform(corpus)

    tf = pd.DataFrame(document_term_matrix.toarray(), columns=cv.get_feature_names())  # TF (Term Frequency)

    D = len(tf)
    df = tf.astype(bool).sum(axis=0)
    idf = np.log((D+1) / (df+1)) + 1             # IDF (Inverse Document Frequency)

    # TF-IDF (Term Frequency-Inverse Document Frequency)
    tfidf = tf * idf                      
    tfidf = tfidf / np.linalg.norm(tfidf, axis=1, keepdims=True)
    
    return tfidf

In [29]:
tfidf_twitter = tfdif(twitter['내용'])

c:\Users\withus\.conda\envs\ML\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [30]:
tfidf_twitter

,10,14,180석,180석으로,18특별법,18특별법 3특별법,1년,2020년,20대,21대,...,확정한 모든,횡포를,횡포를 막기,효과가,효과는,효과를,후에,훨씬,휴머니즘이다,힘을
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2491,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.654278,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2492,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2493,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2494,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2495,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
import pickle

tfidf_twitter.to_pickle('./tfidf_df/tfidf_twitter.pkl')